**TASK:** import numpy

In [1]:
import numpy as np

**TASK:** define vector 'x' with three coordinates

In [2]:
x = np.array([1,2,3])
x

array([1, 2, 3])

**TASK:** define (2 x 2) matrix 'A' 


In [3]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

**TASK:** define (2 x 2) matrix 'B'

In [11]:
B = np.array([[6,7],[8,9]])
B

array([[6, 7],
       [8, 9]])

**TASK:** check the type of 'x'

In [5]:
type(x)

numpy.ndarray

**TASK:** check the type of 'A'

In [6]:
type(A)

numpy.ndarray

**TASK:**  check the shape of 'x'


In [7]:
x.shape

(3,)

**TASK:** check the type of 'A'

In [8]:
A.shape

(2, 2)

**TASK:** 

In [9]:
"""
Define function 'have_same_shape' which checks if two arrays have same shape.

PARAMS:
    array_1 (numpy.ndarray) - first array
    array_2 (numpy.ndarray) - second array
RETURN:
    True - if arrays have same shape
    False - if arrays do not have same shape

Also print 'Arrays must have same shape!' when returning False
"""

"\nDefine function 'have_same_shape' which checks if two arrays have same shape.\n\nPARAMS:\n    array_1 (numpy.ndarray) - first array\n    array_2 (numpy.ndarray) - second array\nRETURN:\n    True - if arrays have same shape\n    False - if arrays do not have same shape\n\nAlso print 'Arrays must have same shape!' when returning False\n"

In [12]:
array_1 = np.array([[6,7],[8,9]])
array_2 = np.array([[1,2],[3,4]])
def have_same_shape(array_1,array_2):
    if array_1.shape == array_2.shape:
        return True
    else:
        return False,"Arrays must have same shape!"
    
have_same_shape(array_1,array_2)

True

**TASK:** call the function 'have_same_shape' with matrix 'A' and vector 'x' as inputs

In [14]:
have_same_shape(A,x)

(False, 'Arrays must have same shape!')

**TASK:**  call the function 'have_same_shape' with matrix 'A' and matrix 'B' as inputs

In [15]:
have_same_shape(A,B)

True

**TASK:** 

In [16]:
"""
Define function 'matrix_addition' which perform matrix addition value by value.

PARAMS:
    A (numpy.ndarray) - first array
    B (numpy.ndarray) - second array
RETURN:
    C (numpy.ndarray) - new A+B array

In this task do not consider broadcasting.
Do not forget to check arrays shapes (you can use 'have_same_shape' function defined before)

"""


"\nDefine function 'matrix_addition' which perform matrix addition value by value.\n\nPARAMS:\n    A (numpy.ndarray) - first array\n    B (numpy.ndarray) - second array\nRETURN:\n    C (numpy.ndarray) - new A+B array\n\nIn this task do not consider broadcasting.\nDo not forget to check arrays shapes (you can use 'have_same_shape' function defined before)\n\n"

In [17]:
def matrix_addition(A,B):
    A = np.array([[11,12],[13,14]])
    B = np.array([[15,16],[17,18]])
    C = A + B 
    return C
print(matrix_addition(A,B))
have_same_shape(A,B)

[[26 28]
 [30 32]]


True

**TASK:** call the function 'matrix_addition' with matrix 'A' and matrix 'B' as inputs

In [18]:
matrix_addition(A,B)

array([[26, 28],
       [30, 32]])

**TASK:** 

In [19]:
"""
Define 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition

PARAMS:
   lst_of_arr (list) - list of numpy.ndarrays
RETURN:
    NEW_ARRAY (numpy.ndarray) - new array

Use 'matrix_addition' function defined before.
"""

"\nDefine 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition\n\nPARAMS:\n   lst_of_arr (list) - list of numpy.ndarrays\nRETURN:\n    NEW_ARRAY (numpy.ndarray) - new array\n\nUse 'matrix_addition' function defined before.\n"

In [20]:
lst_of_arr = np.array([A,A,B,B,B])
def multiple_matrix_addition(lst_of_arr):
    NEW_ARRAY = np.zeros(lst_of_arr[0].shape)
    for i in lst_of_arr:
        NEW_ARRAY += i
        print(NEW_ARRAY)
        
multiple_matrix_addition(lst_of_arr)

[[1. 2.]
 [3. 4.]]
[[2. 4.]
 [6. 8.]]
[[ 8. 11.]
 [14. 17.]]
[[14. 18.]
 [22. 26.]]
[[20. 25.]
 [30. 35.]]


**TASK:** call the function 'multiple_matrix_addition' with matrix [A,A,B,B,B] as input


In [21]:
multiple_matrix_addition([A,A,B,B,B])


[[1. 2.]
 [3. 4.]]
[[2. 4.]
 [6. 8.]]
[[ 8. 11.]
 [14. 17.]]
[[14. 18.]
 [22. 26.]]
[[20. 25.]
 [30. 35.]]


**TASK:** 

In [22]:
"""
Define function 'can_multiply' that checks if two arrays (matrices) can be multiplied

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    True - if arrays can be multiplied, also print the shape of the new array
    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'
    
"""

"\nDefine function 'can_multiply' that checks if two arrays (matrices) can be multiplied\n\nPARAMS:\n   array_a (numpy.ndarray) - first array\n   array_b (numpy.ndarray) - second array\nRETURN:\n    True - if arrays can be multiplied, also print the shape of the new array\n    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'\n    \n"

In [24]:
array_a = np.array([[3,3],[2,4],[1,1]])
array_b = np.array([[3,1],[3,4]])

def can_multiply(array_a,array_b):
    if array_a.shape[1]!=array_b.shape[0]:
        print("Matrices can not be multiplied.")
        return False
    else:
        
        array_c = np.dot(array_a,array_b)
        print(array_c.shape)
        return True
        
    
can_multiply(array_a,array_b)

(3, 2)


True

**TASK:** call the function 'can_multiply' with matrix 'A' and 'B' as inputs

In [25]:
can_multiply(A,B)


(2, 2)


True

**TASK:**  define matrix (3 x 2) matrix C

In [26]:
C = np.array([[1,2],[3,4],[4,5]])
C

array([[1, 2],
       [3, 4],
       [4, 5]])

**TASK:**  call the function 'can_multiply' with matrix 'A' and 'C' as inputs

In [27]:
can_multiply(A,C)

Matrices can not be multiplied.


False

**TASK:**  call the function 'can_multiply' with matrix 'C' and 'A' as inputs (now C,A not A,C). Do you know why is the result different?

In [28]:
can_multiply(C,A)


(3, 2)


True

**TASK:** 

In [29]:
"""
Define function 'matrix_multiplication' that multiply two numpy.ndarrays

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    NEW_ARRAY (numpy.ndarray) - new A * B array
    
Do not forget to check if two matrices can be multiplied.

"""

"\nDefine function 'matrix_multiplication' that multiply two numpy.ndarrays\n\nPARAMS:\n   array_a (numpy.ndarray) - first array\n   array_b (numpy.ndarray) - second array\nRETURN:\n    NEW_ARRAY (numpy.ndarray) - new A * B array\n    \nDo not forget to check if two matrices can be multiplied.\n\n"

In [30]:
def matrix_multiplication(array_a,array_b):
    NEW_ARRAY = np.dot(array_a,array_b)
    return NEW_ARRAY
if can_multiply(array_a,array_b)== True:
    print(matrix_multiplication(array_a,array_b))
else:
    print(can_multiply(array_a,array_b))

(3, 2)
[[18 15]
 [18 18]
 [ 6  5]]


**TASK:**  call the function 'matrix_multiplication' with matrix 'C' and 'B' 


In [31]:
matrix_multiplication(C,B)


array([[22, 25],
       [50, 57],
       [64, 73]])

**TASK:** call the function 'matrix_multiplication' with matrix 'A' and 'C' 

In [32]:
matrix_multiplication(A,C)


ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)