# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [2]:
null = np.zeros(10)

#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [3]:
nullx = np.zeros(10)
nullx[5]=1

#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [4]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5.  Reverse a vector (first element becomes last) (★☆☆)

In [5]:
a=a[::-1]
a

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 6.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [7]:
b = np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [9]:
c = np.nonzero([1,2,0,0,4,0])
c

(array([0, 1, 4], dtype=int64),)

#### 8. Create a 3x3x3 array with random values (★☆☆)

In [10]:
d = np.random.uniform((3,3,3))
d

array([1.9642566 , 1.02166158, 1.80349306])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [12]:
e = np.random.random((10,10))
mini, maxi = e.min(), e.max()
print(mini) 
maxi

0.003541372395311382


0.9996918734361266

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [13]:
f = np.random.random(10)
mean= f.mean()
mean

0.43239329089295825

#### 11. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
g = np.ones((10,10))
g[1:-1,1:-1]=0
g

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 12. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [19]:
h = np.ones((3,3))
print (h)
h = np.pad(h, pad_width=1, mode='constant', constant_values=0)
print (h)           

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 13. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [20]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 14. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [22]:
i = np.diag(1+np.arange(4), k=-1)
i

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 15. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [23]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 16. Normalize a 5x5 random matrix (★☆☆)

In [25]:
j = np.random.random((5,5))
jmax, jmin = j.max(), j.min()
yj= (j-jmin)/(jmax-jmin)
print(j)

[[0.81613273 0.9893869  0.86057857 0.61530751 0.27540105]
 [0.15129301 0.73065393 0.06192315 0.83133352 0.49603552]
 [0.94793622 0.27568013 0.4502043  0.9763586  0.67904891]
 [0.19876807 0.54748836 0.72019792 0.15093254 0.2197471 ]
 [0.37055405 0.05576726 0.70170466 0.31845234 0.15184681]]


#### 17. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
k = np.arange(9)
k[(k>=3)&(k<=8)]*=-1
print(k)

[ 0  1  2 -3 -4 -5 -6 -7 -8]


#### 18. How to round away from zero a float array ? (★☆☆)

In [27]:
def round_array(x,y):
    return np.round(x,y)
test = np.array([69.69, 44.66, 0.5567])
print(round_array(test,0))

[70. 45.  1.]


#### 19. Find common values between two arrays? (★☆☆)

In [28]:
x = np.array([0, 1, 2, 3, 4]) 
y = np.array([0, 2, 4])
print(np.intersect1d(x, y))

[0 2 4]


#### 20. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [29]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\bevli\AppData\Local\Temp/ipykernel_21884/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 21. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [30]:
def generator(): 
    for i in range(10):
        yield i
        
a = np.fromiter(generator(), dtype=float, count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [31]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 23. Create a random vector of size 10 and sort it (★★☆)

In [34]:
a = np.random.random(10)
a.sort()
print(Z)

[0.01339224 0.04544509 0.18993324 0.35381419 0.48716767 0.56001181
 0.59501838 0.77405556 0.83978969 0.93789272]


#### 24. Consider two random arrays A and B, check if they are equal (★★☆)

In [35]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


#### 25. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [36]:
A = np.random.random(10)
A[A.argmax()] = 0
print(A)

[0.86638628 0.79426689 0.52040101 0.61901545 0.60190529 0.
 0.64527196 0.58250951 0.41199451 0.81813844]


#### 26. Find the closest value to random element in a vector? (★★☆)

In [38]:
def find_nearest(array, value):
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    return array[idx]

array = np.random.random(10)
value = 0.5
print(find_nearest(array, value))

0.5063567263253062


#### 27. Convert a float (32 bits) array into an integer (32 bits) in place?

In [39]:
print(np.arange(10, dtype=np.int32))
print(A.astype(np.float32, copy=False))

[0 1 2 3 4 5 6 7 8 9]
[0.8663863  0.7942669  0.520401   0.61901546 0.6019053  0.
 0.64527196 0.5825095  0.41199452 0.8181384 ]


#### 28. Sort an array by the nth column? (★★☆)

In [40]:
l = np.random.randint(0,10,(3,3))
print(l)
print(l[l[:,1].argsort()])

[[8 5 2]
 [1 3 2]
 [7 0 6]]
[[7 0 6]
 [1 3 2]
 [8 5 2]]


#### 29. Find if a given 2D array has null (empty) columns? (★★☆)

In [43]:
m = np.random.randint(0,3,(3,10))
print (m)
print((~m.any(axis=0)).any())

[[0 1 0 0 0 0 1 1 0 2]
 [0 0 2 0 0 2 2 2 1 2]
 [2 0 0 0 1 0 0 2 2 1]]
True


#### 30. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [44]:
n = np.array([1,2,3,4,5])
nn = 3
nzero = np.zeros(len(n) + (len(n)-1)*(nn))
nzero[::nn+1] = n
print(nzero)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 31. Swap two rows of an array? (★★★)

In [49]:
o = np.arange(25).reshape(5,5)
o[[0,1]] = o[[1,0]]
o

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 32. How to negate a boolean value inside an array? (★★★)

In [51]:
p = np.random.randint(0,2,100)
print('original: ')
print(p)
print(np.logical_not(p, out=p))

original: 
[1 0 0 0 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 0 1 1 1 0 1 0 0 1 0 0
 1 1 0 1 1 0 0 1 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 1 1 1 1 1 1 1 0 0 1 0 1 0 1
 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 1 1 1 0 1 0 0 0 1]
[0 1 1 1 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 1 0 0 0 1 0 1 1 0 1 1
 0 0 1 0 0 1 1 0 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0 1 0
 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 0 0 0 1 0 1 1 1 0]


#### 33. Find the most frequent value in an array?

In [52]:
p = np.random.randint(0,10,50)
print(p)
print('rank:', np.bincount(p).argmax())

[8 1 0 7 1 0 4 2 7 1 3 5 0 1 6 4 2 9 3 6 8 2 8 4 9 5 6 9 3 2 3 0 8 1 2 9 9
 7 2 1 3 6 1 7 1 1 7 0 1 6]
rank: 1


#### 34. Get the n largest values of an array (★★★)

In [54]:
q = np.arange(10000)
np.random.shuffle(q)
n = 100
print (q[np.argpartition(-q,n)[:n]])

[9996 9972 9997 9969 9973 9990 9971 9980 9974 9987 9998 9981 9967 9978
 9968 9995 9994 9989 9993 9975 9999 9982 9985 9976 9991 9983 9986 9966
 9970 9988 9984 9992 9979 9977 9965 9953 9949 9957 9955 9943 9946 9950
 9964 9954 9945 9960 9958 9942 9962 9952 9961 9947 9956 9948 9963 9944
 9951 9959 9941 9932 9922 9927 9939 9926 9916 9917 9914 9930 9919 9931
 9938 9921 9934 9933 9937 9935 9940 9923 9913 9915 9928 9929 9918 9912
 9936 9924 9925 9920 9911 9904 9906 9910 9907 9908 9905 9903 9909 9902
 9901 9900]


#### 35. Extract unique rows from a two dimensional array? (★★★)

In [55]:
r = np.random.randint(0,2,(6,3))
s = np.ascontiguousarray(r).view(np.dtype((np.void, r.dtype.itemsize * r.shape[1])))
_, idx = np.unique(s, return_index=True)
rs = r[idx]
print(rs)

[[0 0 0]
 [0 1 0]
 [1 0 0]
 [1 1 1]]
